name: Makefile CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Arm GCC
      run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi

    - name: Set up Ruby
      uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
      with:
        ruby-version: '3.1'

    - name: Install Ceedling
      run: gem install ceedling

    - name: Run test
      run: ceedling test:all

