name: Makefile CI

on:
  push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Arm GCC
      run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi

    - name: Install Ruby and Ceedling
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full
        gem install ceedling

    - name: Run clean
      run: make clean

    - name: Run test
      run: make test

